#!/usr/bin/env python3
"""General SLURM/HPC helper, shared across projects.

Subcommands: configure, discover, submit, status, sync, fetch, pull, push.

No cluster/path knowledge is hardcoded here — projects may live anywhere on
disk (the root is found by walking up, see `find_project_root`), and each
configures its own cluster(s) once:

    make configure CLUSTER=alex REMOTE=/home/hpc/b314bb/b314bb13/projects/so4

This saves to <project_root>/hpc.local.mk (auto-generated, one REMOTE_<cluster>
line per configured cluster + a DEFAULT_CLUSTER). Later calls fall back to
that file when --cluster is omitted, and to the tracked cluster in RUNS.md
for sync. Subdirectory remote paths are that project's REMOTE root + the
local path's position relative to the project root (mirrors local structure).

`pull`/`push` are the manual, whole-directory raw sync (run from anywhere in
the project; mirrors cwd). `sync`/`fetch` are the smarter, run-dir-aware
wrappers used for simulation results specifically.

RUNS.md (in the project root) is a submission ledger, one row per `submit`,
with a Status column that `status` updates in place.

SAFETY: `submit` never runs sbatch unless called with --confirm. Without it,
it only prints what *would* be submitted. Jobs cost real money/allocation —
callers (including the calling agent) must get explicit human confirmation
for the specific job before ever passing --confirm.
"""

# `X | None` and friends in signatures are evaluated at import time on 3.9,
# which is still what bare `python3` resolves to on stock macOS. Keeping
# annotations lazy means this runs anywhere with 3.7+ rather than only where
# the caller happens to have a modern interpreter first on PATH.
from __future__ import annotations

import argparse
import re
import subprocess
import sys
from datetime import datetime
from pathlib import Path

SBATCH_SCRIPT_NAMES = ("srun.sh", "submit.sh", "run.sh", "job.sh")
RUNS_HEADER = (
    "| Date | Cluster | Dir | Job ID | Job Name | Status |\n"
    "|---|---|---|---|---|---|\n"
)


def find_project_root(start: Path) -> Path:
    """Walk up from `start` to the enclosing project root.

    Projects can live anywhere on disk — nothing here assumes a common parent
    directory. Markers are tried in order of how definitive they are, each
    across the whole ancestor chain before falling through to the next:

    1. `hpc.local.mk` — written by `configure`, so it is the unambiguous
       marker once a project has been set up.
    2. a `Makefile` that includes `hpc.mk` — the bootstrap case, before the
       first `configure`. The include check matters: run dirs often carry
       their own unrelated Makefile.
    3. `.git` — last resort for a project that has neither yet.
    """
    start = start.resolve()
    if start.is_file():
        start = start.parent
    chain = [start, *start.parents]

    for d in chain:
        if (d / "hpc.local.mk").is_file():
            return d

    for d in chain:
        makefile = d / "Makefile"
        if makefile.is_file():
            try:
                if "hpc.mk" in makefile.read_text(errors="ignore"):
                    return d
            except OSError:
                pass

    for d in chain:
        if (d / ".git").exists():
            return d

    raise SystemExit(
        f"Could not locate a project root above {start}.\n"
        "Expected one of: an hpc.local.mk, a Makefile that includes hpc.mk, "
        "or a git repository."
    )


def rel_to_project(path: Path, project_root: Path) -> str:
    rel = path.resolve().relative_to(project_root.resolve())
    return str(rel) if str(rel) != "." else ""


# ── Per-project config (hpc.local.mk) ───────────────────────────────────────


def config_path(project_root: Path) -> Path:
    return project_root / "hpc.local.mk"


def read_config(project_root: Path) -> dict:
    p = config_path(project_root)
    if not p.exists():
        return {}
    cfg = {}
    for line in p.read_text().splitlines():
        m = re.match(r"^(\w+)\s*:=\s*(.+?)\s*$", line)
        if m:
            cfg[m.group(1)] = m.group(2)
    return cfg


def write_config(project_root: Path, cluster: str, remote: str) -> None:
    cfg = read_config(project_root)
    cfg[f"REMOTE_{cluster}"] = remote
    cfg["DEFAULT_CLUSTER"] = cluster
    lines = [
        "# Auto-generated by `make configure` — per-project remote defaults.",
        "# Safe to hand-edit; re-running configure for a cluster overwrites just that line.",
    ]
    for k in sorted(k for k in cfg if k.startswith("REMOTE_")):
        lines.append(f"{k} := {cfg[k]}")
    lines.append(f"DEFAULT_CLUSTER := {cfg['DEFAULT_CLUSTER']}")
    config_path(project_root).write_text("\n".join(lines) + "\n")


def resolve_cluster(project_root: Path, cluster: str | None) -> str:
    cluster = cluster or read_config(project_root).get("DEFAULT_CLUSTER")
    if not cluster:
        raise SystemExit(
            "No cluster configured for this project.\n"
            "Run: make configure CLUSTER=<name> REMOTE=<absolute remote path for this project>"
        )
    return cluster


def resolve_remote_root(project_root: Path, cluster: str) -> str:
    key = f"REMOTE_{cluster}"
    cfg = read_config(project_root)
    if key not in cfg:
        raise SystemExit(
            f"No remote path configured for cluster '{cluster}' in this project.\n"
            f"Run: make configure CLUSTER={cluster} REMOTE=<absolute remote path for this project>"
        )
    return cfg[key]


def remote_path(local_path: Path, project_root: Path, cluster: str) -> str:
    root = resolve_remote_root(project_root, cluster)
    rel = rel_to_project(local_path, project_root)
    return f"{root}/{rel}".rstrip("/")


def raw_rsync(
    direction: str, cluster: str, local_dir: Path, project_root: Path, excludes: list[str]
) -> None:
    """Mirror local_dir <-> its remote counterpart."""
    remote = f"{cluster}:{remote_path(local_dir, project_root, cluster)}/"
    local = f"{local_dir}/"
    src, dst = (remote, local) if direction == "from" else (local, remote)
    exclude_args = [a for pat in excludes for a in ("--exclude", pat)]
    cmd = ["rsync", "-zavm", "--include=*/", "--exclude=.*", *exclude_args, src, dst]
    subprocess.run(cmd, check=True)


# ── Run-dir discovery ────────────────────────────────────────────────────────


def is_submit_script(p: Path) -> bool:
    if p.name not in SBATCH_SCRIPT_NAMES:
        return False
    try:
        return "#SBATCH" in p.read_text()
    except (UnicodeDecodeError, OSError):
        return False


def discover_run_dirs(root: Path) -> list[Path]:
    return sorted({p.parent for p in root.rglob("*.sh") if is_submit_script(p)})


def parse_sbatch_directives(script: Path) -> dict:
    text = script.read_text()
    directives = {}
    for m in re.finditer(r"^#SBATCH\s+(--?[\w-]+)(?:[= ]([^\n#]+))?", text, re.MULTILINE):
        directives[m.group(1).lstrip("-")] = (m.group(2) or "").strip() or True
    return directives


# ── RUNS.md ──────────────────────────────────────────────────────────────────


def runs_md_path(project_root: Path) -> Path:
    return project_root / "RUNS.md"


def read_run_rows(project_root: Path) -> list[list[str]]:
    p = runs_md_path(project_root)
    if not p.exists():
        return []
    rows = []
    for line in p.read_text().splitlines()[2:]:  # skip header + separator
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) == 6:
            rows.append(cells)
    return rows


def append_run(project_root: Path, cluster: str, rel_dir: str, job_id: str, job_name: str):
    p = runs_md_path(project_root)
    if not p.exists():
        p.write_text(RUNS_HEADER)
    date = datetime.now().strftime("%Y-%m-%d %H:%M")
    with p.open("a") as f:
        f.write(f"| {date} | {cluster} | {rel_dir} | {job_id} | {job_name} | SUBMITTED |\n")


def update_status(project_root: Path, job_id: str, status: str):
    p = runs_md_path(project_root)
    if not p.exists():
        return
    lines = p.read_text().splitlines(keepends=True)
    out = []
    for line in lines:
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) == 6 and cells[3] == job_id:
            cells[5] = status
            line = "| " + " | ".join(cells) + " |\n"
        out.append(line)
    p.write_text("".join(out))


def latest_cluster_for_dir(project_root: Path, rel_dir: str) -> str | None:
    cluster = None
    for cells in read_run_rows(project_root):
        if cells[2] == rel_dir:
            cluster = cells[1]
    return cluster


# ── Subcommands ────────────────────────────────────────────────────────────


def cmd_configure(args):
    project_root = find_project_root(Path.cwd())
    write_config(project_root, args.cluster, args.remote)
    print(f"Saved {config_path(project_root)}: CLUSTER={args.cluster} REMOTE={args.remote}")


def cmd_discover(args):
    root = find_project_root(Path.cwd())
    dirs = discover_run_dirs(root)
    if not dirs:
        print("No submit scripts found.")
        return
    for d in dirs:
        rel_dir = str(d.relative_to(root))
        cluster = latest_cluster_for_dir(root, rel_dir)
        print(f"{rel_dir}" + (f"  (last: {cluster})" if cluster else "  (never submitted)"))


def cmd_submit(args):
    dir_path = Path(args.dir).resolve()
    project_root = find_project_root(dir_path)
    cluster = resolve_cluster(project_root, args.cluster)

    script = next(
        (dir_path / n for n in SBATCH_SCRIPT_NAMES if is_submit_script(dir_path / n)),
        None,
    )
    if script is None:
        raise SystemExit(f"No submit script ({', '.join(SBATCH_SCRIPT_NAMES)}) found in {dir_path}")

    directives = parse_sbatch_directives(script)
    rel_dir = rel_to_project(dir_path, project_root)
    rpath = remote_path(dir_path, project_root, cluster)

    print("About to submit:")
    print(f"  cluster:    {cluster}")
    print(f"  local dir:  {dir_path}")
    print(f"  remote dir: {rpath}")
    print(f"  script:     {script.name}")
    for k in ("job-name", "partition", "time", "nodes", "ntasks", "gpus-per-node", "cpus-per-task", "constraint"):
        if k in directives:
            print(f"  {k}: {directives[k]}")

    if not args.confirm:
        print("\nDRY RUN ONLY — no job submitted. Re-run with --confirm to actually submit.")
        return

    remote_cmd = f"cd {rpath} && sbatch {script.name}"
    result = subprocess.run(["ssh", cluster, remote_cmd], capture_output=True, text=True)
    print(result.stdout)
    if result.returncode != 0:
        print(result.stderr, file=sys.stderr)
        raise SystemExit(result.returncode)

    m = re.search(r"Submitted batch job (\d+)", result.stdout)
    if not m:
        print("WARNING: could not parse job ID from sbatch output.", file=sys.stderr)
        return
    job_id = m.group(1)
    job_name = directives.get("job-name") or dir_path.name
    append_run(project_root, cluster, rel_dir, job_id, job_name)
    print(f"Job {job_id} submitted, recorded in {runs_md_path(project_root)}")


TERMINAL_STATES = {"COMPLETED", "FAILED", "CANCELLED", "TIMEOUT", "OUT_OF_MEMORY", "NODE_FAIL"}


def cmd_status(args):
    project_root = find_project_root(Path.cwd())
    rows = read_run_rows(project_root)
    if not rows:
        print("No RUNS.md entries found.")
        return

    by_cluster: dict[str, list[list[str]]] = {}
    for cells in rows:
        _, cluster, rel_dir, job_id, job_name, status = cells
        if status.upper() in TERMINAL_STATES:
            continue
        by_cluster.setdefault(cluster, []).append(cells)

    if not by_cluster:
        print("All tracked jobs are in a terminal state (see RUNS.md).")
        return

    for cluster, jobs in by_cluster.items():
        job_ids = ",".join(c[3] for c in jobs)
        result = subprocess.run(
            ["ssh", cluster, f"squeue -j {job_ids} --noheader --format='%i %T'"],
            capture_output=True, text=True,
        )
        live = dict(line.split() for line in result.stdout.splitlines() if line.strip())
        for cells in jobs:
            _, _, rel_dir, job_id, job_name, _ = cells
            state = live.get(job_id)
            if state is None:
                sacct = subprocess.run(
                    ["ssh", cluster, f"sacct -j {job_id} --noheader --format=State -X"],
                    capture_output=True, text=True,
                )
                out = sacct.stdout.strip().split()
                state = out[0] if out else "UNKNOWN"
            update_status(project_root, job_id, state)
            print(f"{cluster:6s} {job_id:10s} {rel_dir:30s} {job_name:20s} {state}")


def cmd_sync(args):
    root = find_project_root(Path.cwd())
    for d in discover_run_dirs(root):
        rel_dir = str(d.relative_to(root))
        cluster = latest_cluster_for_dir(root, rel_dir)
        if cluster is None:
            print(f"skip {rel_dir}: never submitted / no tracked cluster in RUNS.md")
            continue
        if args.cluster and cluster != args.cluster:
            continue
        print(f"\n--- {rel_dir}  <-  {cluster} ---")
        try:
            raw_rsync("from", cluster, d, root, [])
        except SystemExit as e:
            print(f"skip {rel_dir}: {e}")


def cmd_fetch(args):
    dir_path = Path(args.dir).resolve()
    project_root = find_project_root(dir_path)
    cluster = resolve_cluster(project_root, args.cluster)
    raw_rsync("from", cluster, dir_path, project_root, [])


def cmd_pull(args):
    project_root = find_project_root(Path.cwd())
    cluster = resolve_cluster(project_root, args.cluster)
    raw_rsync("from", cluster, Path.cwd(), project_root, args.exclude or [])


def cmd_push(args):
    project_root = find_project_root(Path.cwd())
    cluster = resolve_cluster(project_root, args.cluster)
    raw_rsync("to", cluster, Path.cwd(), project_root, args.exclude or [])


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    sub = ap.add_subparsers(dest="command", required=True)

    p_configure = sub.add_parser("configure", help="save CLUSTER/REMOTE defaults for this project")
    p_configure.add_argument("--cluster", required=True)
    p_configure.add_argument("--remote", required=True, help="absolute remote path for this project's root")

    sub.add_parser("discover")

    p_submit = sub.add_parser("submit")
    p_submit.add_argument("dir")
    p_submit.add_argument("--cluster")
    p_submit.add_argument("--confirm", action="store_true")

    sub.add_parser("status")

    p_sync = sub.add_parser("sync")
    p_sync.add_argument("--cluster")

    p_fetch = sub.add_parser("fetch")
    p_fetch.add_argument("dir")
    p_fetch.add_argument("--cluster")

    p_pull = sub.add_parser("pull", help="manual: pull cwd from remote")
    p_pull.add_argument("--cluster")
    p_pull.add_argument("--exclude", action="append")

    p_push = sub.add_parser("push", help="manual: push cwd to remote")
    p_push.add_argument("--cluster")
    p_push.add_argument("--exclude", action="append")

    args = ap.parse_args()
    dispatch = {
        "configure": cmd_configure,
        "discover": cmd_discover,
        "submit": cmd_submit,
        "status": cmd_status,
        "sync": cmd_sync,
        "fetch": cmd_fetch,
        "pull": cmd_pull,
        "push": cmd_push,
    }
    dispatch[args.command](args)


if __name__ == "__main__":
    main()
